image: maven:latest

stages:
  - build
  - unit_test
  - upload
  - deploy_stage
  - acceptance_test
  - deploy_product

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

  STAGE_BASE_URL: "http://192.168.33.17:8090"

cache:
  paths:
    - target/

build_app:
  stage: build
  tags:
  - integration
  script:
    - mvn package -DskipTests

unit_test_app:
  stage: unit_test
  tags:
  - integration
  script:
    - mvn surefire:test@JUnit-execution

upload_app:
    stage: upload
    tags:
    - integration
    script:
    - echo "upload app"
    artifacts:
        name: "my-app"
        paths:
        - target/*.jar
        
deploy_stage:
    stage: deploy_stage
    tags:
    - stage-vm-shell
    script:
    - sudo cp target/*.jar /home/vagrant/SEE.jar
    - nohup java -jar /home/vagrant/SEE.jar > /dev/null 2>&1 &

acc_test_app:
  stage: acceptance_test
  tags:
    - integration
  services:
    - name: selenium/standalone-chrome:latest
  script:
    - mvn surefire:test@TestNg-execution -Denv.BASEURL=$STAGE_BASE_URL


deploy_product:
    stage: deploy_product
    tags:
    - product-vm-shell
    script:
    - sudo cp target/*.jar /home/vagrant/SEE.jar
    - nohup java -jar /home/vagrant/SEE.jar > /dev/null 2>&1 &
